name: NodeJS with Grunt

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
  pull_request:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.3

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      -  name: Build application
         run: npm run build
         
